# Generated by Codex on 2026-06-27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_invitation_sent_date"),
        ("engine", "0106_add_interval_annotations"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameExtractionSession",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("saved", "Saved"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("rq_id", models.CharField(blank=True, default="", max_length=255)),
                ("source_paths", models.JSONField(default=list)),
                ("frame_interval", models.PositiveIntegerField(default=25)),
                ("rotate_angle", models.IntegerField(default=0)),
                ("deduplicate", models.BooleanField(default=True)),
                ("duplicate_threshold", models.PositiveSmallIntegerField(default=4)),
                ("recursive", models.BooleanField(default=True)),
                ("image_quality", models.PositiveSmallIntegerField(default=95)),
                ("processing_backend", models.CharField(default="auto", max_length=16)),
                ("work_share_path", models.CharField(blank=True, default="", max_length=1024)),
                ("output_share_path", models.CharField(blank=True, default="", max_length=1024)),
                ("total_videos", models.PositiveIntegerField(default=0)),
                ("processed_videos", models.PositiveIntegerField(default=0)),
                ("failed_videos", models.PositiveIntegerField(default=0)),
                ("sampled_frames", models.PositiveIntegerField(default=0)),
                ("kept_frames", models.PositiveIntegerField(default=0)),
                ("duplicate_frames", models.PositiveIntegerField(default=0)),
                ("used_backend", models.CharField(blank=True, default="", max_length=32)),
                ("error", models.TextField(blank=True, default="")),
                ("started_date", models.DateTimeField(blank=True, null=True)),
                ("finished_date", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frame_extraction_sessions",
                        related_query_name="frame_extraction_session",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frame_extraction_sessions",
                        related_query_name="frame_extraction_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FrameExtractionFrame",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("file_path", models.CharField(max_length=1024)),
                ("source_path", models.CharField(max_length=1024)),
                ("video_index", models.PositiveIntegerField(default=0)),
                ("source_frame", models.PositiveIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("excluded", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        related_query_name="frame",
                        to="engine.frameextractionsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="frameextractionsession",
            index=models.Index(fields=["owner", "status"], name="engine_fram_owner_i_408ea4_idx"),
        ),
        migrations.AddIndex(
            model_name="frameextractionsession",
            index=models.Index(
                fields=["organization", "status"], name="engine_fram_organiz_d083df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frameextractionsession",
            index=models.Index(fields=["created_date"], name="engine_fram_created_b0de81_idx"),
        ),
        migrations.AddIndex(
            model_name="frameextractionframe",
            index=models.Index(
                fields=["session", "excluded", "order"], name="engine_fram_session_778a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frameextractionframe",
            index=models.Index(fields=["session", "order"], name="engine_fram_session_b5a89e_idx"),
        ),
        migrations.AddConstraint(
            model_name="frameextractionframe",
            constraint=models.UniqueConstraint(
                fields=("session", "order"), name="unique_frame_extraction_frame_order"
            ),
        ),
    ]
