services:
  nuclio:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.16.3-amd64
    restart: always
    networks:
      - cvat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      http_proxy:
      https_proxy:
      no_proxy: ${no_proxy:-}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
      NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"

  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
      CVAT_LOCAL_MODEL_DEPLOYMENT: 1
      CVAT_LOCAL_MODEL_DEPLOYMENT_TIMEOUT: 1800
      CVAT_LOCAL_MODEL_DEPLOYMENT_BASE_IMAGE: ${CVAT_LOCAL_MODEL_DEPLOYMENT_BASE_IMAGE:-python:3.10-slim}
      CVAT_LOCAL_MODEL_DEPLOYMENT_NO_BASE_IMAGES_PULL: ${CVAT_LOCAL_MODEL_DEPLOYMENT_NO_BASE_IMAGES_PULL:-0}
      CVAT_LOCAL_MODEL_DEPLOYMENT_PIP_INDEX_URL: ${CVAT_LOCAL_MODEL_DEPLOYMENT_PIP_INDEX_URL:-}
      CVAT_LOCAL_MODEL_DEPLOYMENT_PIP_EXTRA_INDEX_URL: ${CVAT_LOCAL_MODEL_DEPLOYMENT_PIP_EXTRA_INDEX_URL:-}
      CVAT_LOCAL_MODEL_DEPLOYMENT_PIP_TRUSTED_HOST: ${CVAT_LOCAL_MODEL_DEPLOYMENT_PIP_TRUSTED_HOST:-}
      CVAT_LOCAL_MODEL_DEPLOYMENT_INSTALL_DEPENDENCIES: ${CVAT_LOCAL_MODEL_DEPLOYMENT_INSTALL_DEPENDENCIES:-1}
    group_add:
      - "${DOCKER_GID:-0}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:host-gateway"
